// src/FAQ.js

import React, { useState } from 'react';
import styled, { keyframes } from 'styled-components';
import { FaPlus, FaMinus } from 'react-icons/fa'; // Importing React Icons

const fadeIn = keyframes`
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
`;

const Container = styled.div`
  max-width: 1250px;
  margin: 20px auto;
  padding: 20px;
  background: #202020;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
`;

const Title = styled.h2`
  color: white; // Set the color to white
  text-align: center; // Center the title
`;

const Question = styled.div`
  cursor: pointer;
  padding: 15px;
  background: #fff5da;
  border-radius: 5px;
  margin: 10px 0;
  transition: background 0.3s ease;
  display: flex;
  justify-content: space-between;
  align-items: center;

  &:hover {
    background: #d1d1d1;
  }
`;

const Answer = styled.div`
  padding: 10px;
  margin: 5px 0;
  animation: ${fadeIn} 0.5s ease-in;
  color: white; // Set the answer color to white
`;

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const faqs = [
    { question: "How Can I Convert Text to Audio?", answer: "With DinoSpeech, converting text to audio is seamless. Simply log into our platform, input your text, select your desired AI voice, and generate. You can then download the audio in MP3 or WAV format." },
    { question: "What Software Creates the Most Realistic Text-to-Speech (TTS) Voice?", answer: "DinoSpeech offers the most realistic TTS voices in the industry. Our advanced AI technology captures human nuances, delivering a voice experience virtually indistinguishable from an actual human narrator." },
    { question: "Who Voices Our Text-to-Speech?", answer: "Our TTS voices are generated by state-of-the-art AI models, trained on vast datasets to produce lifelike and natural-sounding speech, ensuring top-notch quality and realism." },
    { question: "How Do I Get Different Voices for Text-to-Speech?", answer: "DinoSpeech boasts an expansive library of over 800 AI voices across 142 languages. Simply browse, preview, and select the voice that resonates best with your content." },
    { question: "Is There a Text-to-Voice Software That Will Read a Book for Me?", answer: "Absolutely! DinoSpeech's TTS tool is perfect for converting books into audio. Input the text, choose a voice, and let our AI generate a captivating audiobook for you." },
    { question: "Is There Free Text-to-Speech Software for Dyslexia?", answer: "DinoSpeech offers a version of our TTS tool ideal for individuals with dyslexia, making reading more accessible. Our lifelike voices can assist in comprehension and make content more engaging." },
  ];

  const toggleAnswer = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <Container>
      <Title>FAQs</Title>
      {faqs.map((faq, index) => (
        <div key={index}>
          <Question onClick={() => toggleAnswer(index)}>
            <span>{faq.question}</span>
            {openIndex === index ? <FaMinus /> : <FaPlus />} {/* Using React Icons */}
          </Question>
          {openIndex === index && (
            <Answer>
              {faq.answer}
            </Answer>
          )}
        </div>
      ))}
    </Container>
  );
};

export default FAQ;